"""add password to user_details

Revision ID: 713f2c55bcb9
Revises: 3c1253dab794
Create Date: 2025-11-03 15:28:43.543086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '713f2c55bcb9'
down_revision = '3c1253dab794'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=False))
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_details', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('password')

    # ### end Alembic commands ###
